### ISSUE TITLE
Errors while executing simple command using netmiko module in Pycharm 

### ISSUE THREAD

**Issue by sriramm123** [sriramm123/MS#1]
The same code works when I run ipython or on terminal. But I fails when I execute it in Pycharm..

Code : 
#!/usr/bin/env python
from netmiko import Netmiko
from getpass import getpass

net_conn = Netmiko(host = '17.198.233.14', username = 'sriram_murali', password = getpass(), device_type = 'cisco_ios')
output = net_conn.send_command("show arp")
print(output)

Error:

/Users/smurali/PycharmProjects/untitled2/venv/bin/python /Users/smurali/PycharmProjects/untitled2/LAB.py
Traceback (most recent call last):
  File "/Users/smurali/PycharmProjects/untitled2/LAB.py", line 2, in <module>
    from netmiko import Netmiko
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/base_connection.py", line 28, in <module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured_data
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/netmiko/utilities.py", line 8, in <module>
    import serial.tools.list_ports
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/smurali/PycharmProjects/untitled2/venv/lib/python3.7/site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found

Process finished with exit code 1

**Comment by sriramm123** [comment]
I would need help in fixing this issue in Pycharm.
